# Generated by Django 5.1.15 on 2026-02-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataLayer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "definition_scheme",
                    models.JSONField(
                        default=dict,
                        help_text="Contrato de ingesta: campos obligatorios, tipos y alias para parseo de datos deCSV/sensores.",
                    ),
                ),
                (
                    "evaluation_scheme",
                    models.JSONField(
                        default=dict,
                        help_text="Contrato de  agronomica: ejes kiviat, rangos de colorimetria y preguntas manuales.",
                    ),
                ),
                ("attachments_url", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "datalayers",
                "ordering": ["name"],
            },
        ),
    ]
