# Generated by Django 5.1.15 on 2026-03-02 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalayers", "0001_initial"),
        ("field_ops", "0003_fieldtask"),
        ("geo_assets", "0004_ranchpartner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLayerHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "import_date",
                    models.DateField(
                        help_text="Fecha en que se realizó o corresponde la importación."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        help_text="Cultivo asociado al momento de la importación.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datalayer_headers",
                        to="field_ops.cropcatalog",
                    ),
                ),
                (
                    "datalayer",
                    models.ForeignKey(
                        help_text="Contrato de datos (definition_scheme) que valida esta importación.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="headers",
                        to="datalayers.datalayer",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote geográfico al que pertenece este conjunto de puntos. Si se vincula una task, se hereda automáticamente de task.plot (denormalización).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datalayer_headers",
                        to="geo_assets.plot",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: tarea planificada que originó esta importación.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datalayer_headers",
                        to="field_ops.fieldtask",
                    ),
                ),
            ],
            options={
                "db_table": "datalayer_headers",
                "ordering": ["-import_date"],
                "indexes": [
                    models.Index(fields=["task"], name="idx_dlheaders_task"),
                    models.Index(fields=["plot"], name="idx_dlheaders_plot"),
                    models.Index(fields=["datalayer"], name="idx_dlheaders_datalayer"),
                    models.Index(
                        fields=["import_date"], name="idx_dlheaders_import_date"
                    ),
                ],
            },
        ),
    ]
