# Generated by Django 5.1.15 on 2026-03-02 16:46

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalayers", "0002_add_datalayerheader"),
        ("geo_assets", "0004_ranchpartner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLayerPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Coordenada geografica del punto capturado (WGS84). GiST automaticamente indexado.",
                        srid=4326,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha, hora y segundo en la que se capturó el punto de datos.",
                        null=True,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con los datos necesarios capturados en el punto.Estructura validad en el definition_scheme de DataLayer correspondiente.",
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        help_text="Lote de importación al que pertenece este punto.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="datalayers.datalayerheader",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote geográfico (denormalizado) al que pertenece este punto. Si se vincula una task, se hereda automáticamente de header.plot.Para consultas directas sin JOINs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_points",
                        to="geo_assets.plot",
                    ),
                ),
            ],
            options={
                "db_table": "datalayer_points",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(fields=["header"], name="idx_dlpoints_header"),
                    models.Index(
                        fields=["plot", "captured_at"],
                        name="idx_dlpoints_plot_captured_at",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["raw_data"], name="idx_dlpoints_raw_data"
                    ),
                ],
            },
        ),
    ]
