# Generated by Django 5.1.15 on 2026-03-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalayers", "0003_add_datalayerpoints"),
        ("field_ops", "0004_add_fieldtaskreport_taskreportissue"),
        ("geo_assets", "0004_ranchpartner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalayerheader",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="datalayerheader",
            name="crop",
            field=models.ForeignKey(
                help_text="Opcional: Cultivo asociado al conjunto de datos.\n NOTA: no es necesario si vincula una task.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="datalayer_headers",
                to="field_ops.cropcatalog",
                verbose_name="Cultivo",
            ),
        ),
        migrations.AlterField(
            model_name="datalayerheader",
            name="datalayer",
            field=models.ForeignKey(
                help_text="Contrato de datos (definition_scheme) que valida esta importación.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="headers",
                to="datalayers.datalayer",
                verbose_name="Tipo de analisis/ingesta",
            ),
        ),
        migrations.AlterField(
            model_name="datalayerheader",
            name="import_date",
            field=models.DateField(
                help_text="Fecha en que se realizó o corresponde la importación.",
                verbose_name="Fecha de importación",
            ),
        ),
        migrations.AlterField(
            model_name="datalayerheader",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lote geográfico al que pertenece este conjunto de puntos.\n NOTA: Si vincula una actividad planificada, se hereda automáticoamente la parcela.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datalayer_headers",
                to="geo_assets.plot",
                verbose_name="Parcela",
            ),
        ),
        migrations.AlterField(
            model_name="datalayerheader",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: tarea planificada que contempla la importación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datalayer_headers",
                to="field_ops.fieldtask",
            ),
        ),
    ]
