# Generated by Django 5.1.15 on 2026-03-03 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalayers", "0004_alter_datalayerheader_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalayer",
            name="definition_scheme",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contrato de ingesta: campos obligatorios, tipos y alias para parseo de datos de CSV/sensores.",
            ),
        ),
        migrations.AlterField(
            model_name="datalayer",
            name="evaluation_scheme",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contrato agronomico: ejes kiviat, rangos de colorimetria y preguntas manuales.",
            ),
        ),
        migrations.AlterField(
            model_name="datalayerheader",
            name="import_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Fecha en que se realizó o corresponde la importación.",
                verbose_name="Fecha de importación",
            ),
        ),
    ]
