# Generated by Django 5.1.15 on 2026-03-07 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datalayers", "0005_a1_a2_blank_scheme_default_date"),
        ("datalayers", "0005_rename_raw_data_to_parameters"),
    ]

    operations = []
