# Generated by Django 5.1.15 on 2026-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CropCatalog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("additional_params", models.JSONField(blank=True, default=dict)),
                ("attachments_url", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "crop_catalog",
                "ordering": ["name"],
            },
        ),
    ]
