# Generated by Django 5.1.15 on 2026-02-27 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("field_ops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PestCatalog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ref_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Valor de referencia como umbral de tolerancia",
                        null=True,
                    ),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("additional_params", models.JSONField(blank=True, default=dict)),
                ("attachments_url", models.JSONField(blank=True, default=list)),
                (
                    "default_crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="common_pests",
                        to="field_ops.cropcatalog",
                    ),
                ),
            ],
            options={
                "db_table": "pest_catalog",
                "ordering": ["name"],
            },
        ),
    ]
