# Generated by Django 5.1.15 on 2026-03-01 20:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalayers", "0001_initial"),
        ("field_ops", "0002_pestcatalog"),
        ("geo_assets", "0004_ranchpartner"),
        ("organizations", "0002_contact_agrounit_default_contact_contactassignment"),
        ("users", "0005_userassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voucher_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cycle",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de ciclo inválido. Debe ser YYYY-A o YYYY-B (Ej. 2022-A)",
                                regex="^\\d{4}-[AB]$",
                            )
                        ],
                    ),
                ),
                ("est_start_date", models.DateTimeField(blank=True, null=True)),
                ("est_finish_date", models.DateTimeField(blank=True, null=True)),
                ("actual_start_date", models.DateTimeField(blank=True, null=True)),
                ("actual_finish_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("open", "Abierto"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("expired", "Expirado"),
                            ("closed", "Cerrado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("location_url", models.URLField(blank=True, null=True)),
                ("attachments_url", models.JSONField(blank=True, default=list)),
                (
                    "agro_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_tasks",
                        to="organizations.agrounit",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_tasks",
                        to="field_ops.cropcatalog",
                    ),
                ),
                (
                    "datalayer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_tasks",
                        to="datalayers.datalayer",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_tasks",
                        to="users.individual",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="field_ops.fieldtask",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_tasks",
                        to="geo_assets.plot",
                    ),
                ),
            ],
            options={
                "db_table": "field_tasks",
                "ordering": ["-est_start_date"],
            },
        ),
    ]
