# Generated by Django 5.1.15 on 2026-03-03 00:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("field_ops", "0003_fieldtask"),
        ("geo_assets", "0004_ranchpartner"),
        ("users", "0005_userassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldTaskReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary_data",
                    models.JSONField(
                        default=dict,
                        help_text="Estadísticas calculadas automáticamente: conteo, min/max/avg por campo numérico de raw_data.",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Fecha de generación del reporte (automática).",
                    ),
                ),
                (
                    "evaluation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scores Kiviat, etapa fisiológica GDD y ajustes manuales a la colorimetría.",
                    ),
                ),
                (
                    "scan_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se realizó la toma de datos en campo.",
                        null=True,
                    ),
                ),
                (
                    "report_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Calificación general del desempeño (1-10).",
                        null=True,
                    ),
                ),
                ("main_causes", models.TextField(blank=True, null=True)),
                (
                    "summary_1",
                    models.TextField(
                        blank=True, help_text="Situación actual observada.", null=True
                    ),
                ),
                (
                    "summary_2",
                    models.TextField(
                        blank=True,
                        help_text="Causas identificables y factores externos.",
                        null=True,
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True, help_text="Dictamen final del ingeniero.", null=True
                    ),
                ),
                (
                    "internal_comments",
                    models.TextField(
                        blank=True,
                        help_text="Notas privadas para nivel gerencial.",
                        null=True,
                    ),
                ),
                (
                    "map_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del snapshot del mapa de calor.",
                        null=True,
                    ),
                ),
                (
                    "attachments_url",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array de URLs de fotos de evidencia.",
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "validation_token",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Técnico o ingeniero que generó/validó el reporte.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_reports",
                        to="users.individual",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote denormalizado desde task.plot para consultas rápidas.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_reports",
                        to="geo_assets.plot",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        help_text="Tarea de campo que origina este reporte. 1:1 — cada task tiene máximo un reporte.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="field_ops.fieldtask",
                    ),
                ),
            ],
            options={
                "db_table": "field_task_reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskReportIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "agro_activity",
                    models.CharField(
                        blank=True,
                        help_text="Actividad agronómica relacionada (valores definidos en config).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de issue (valores definidos en config).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        blank=True,
                        help_text="Probabilidad de ocurrencia (0.0 - 1.0).",
                        null=True,
                    ),
                ),
                (
                    "severity_alert",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("expected_solution", models.TextField(blank=True, null=True)),
                ("reached_solution", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("irresoluble", "Irresoluble"),
                            ("solucionada", "Solucionada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "is_ruled",
                    models.BooleanField(
                        default=False,
                        help_text="True cuando el issue está resuelto o marcado como irresoluble.",
                    ),
                ),
                ("identification_date", models.DateField(blank=True, null=True)),
                ("solution_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Reporte del que se deriva este issue.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="field_ops.fieldtaskreport",
                    ),
                ),
            ],
            options={
                "db_table": "task_report_issues",
                "ordering": ["-severity_alert", "status"],
            },
        ),
        migrations.AddIndex(
            model_name="fieldtaskreport",
            index=models.Index(fields=["task"], name="idx_ftreports_task"),
        ),
        migrations.AddIndex(
            model_name="fieldtaskreport",
            index=models.Index(fields=["plot"], name="idx_ftreports_plot"),
        ),
        migrations.AddIndex(
            model_name="fieldtaskreport",
            index=models.Index(fields=["report_date"], name="idx_ftreports_date"),
        ),
        migrations.AddIndex(
            model_name="taskreportissue",
            index=models.Index(fields=["report"], name="idx_tri_report"),
        ),
        migrations.AddIndex(
            model_name="taskreportissue",
            index=models.Index(fields=["status"], name="idx_tri_status"),
        ),
        migrations.AddIndex(
            model_name="taskreportissue",
            index=models.Index(fields=["is_ruled"], name="idx_tri_is_ruled"),
        ),
    ]
