# Generated by Django 5.1.15 on 2026-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("field_ops", "0004_add_fieldtaskreport_taskreportissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cropcatalog",
            name="name",
            field=models.CharField(
                help_text="Variedad de cultivo (ej: Manzana Verde, Mango Manila, Moringa, Calabacin).",
                max_length=200,
                unique=True,
            ),
        ),
    ]
