# Generated by Django 5.1.15 on 2026-02-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="requires_password_change",
            field=models.BooleanField(default=False),
        ),
    ]
