# Generated by Django 5.1.15 on 2026-02-24 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0002_state"),
        ("users", "0002_user_requires_password_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individuals",
                to="geography.country",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individuals",
                to="geography.state",
            ),
        ),
    ]
