# Generated by Django 5.1.15 on 2026-03-04 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Jerarquía: 1=Guest, 2=Technician, 3=Supervisor, 4=Gerente, 5=SuperAdmin",
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
