# Generated by Django 5.1.15 on 2026-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userrole_level_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrole",
            name="activity_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
