# Generated by Django 5.1.15 on 2026-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("iso_2", models.CharField(max_length=2, unique=True)),
                ("iso_3", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
    ]
