# Generated by Django 5.1.15 on 2026-02-24 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "db_table": "states",
                "ordering": ["name"],
                "unique_together": {("country", "code")},
            },
        ),
    ]
