# Generated by Django 5.1.15 on 2026-02-26 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_assets", "0002_ranch_geom_plot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotVertex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertices",
                        to="geo_assets.plot",
                    ),
                ),
            ],
            options={
                "db_table": "plot_vertexes",
                "ordering": ["plot", "level"],
                "unique_together": {("plot", "level")},
            },
        ),
    ]
