# Generated by Django 5.1.15 on 2026-02-26 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_assets", "0003_plotvertex"),
        ("organizations", "0002_contact_agrounit_default_contact_contactassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RanchPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("guild", "Asociación Agrícola"),
                            ("grain_collector", "Acopiadora de Grano"),
                            ("lab", "Laboratorio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranch_relations",
                        to="organizations.agrounit",
                    ),
                ),
                (
                    "ranch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="geo_assets.ranch",
                    ),
                ),
            ],
            options={
                "db_table": "ranch_partners",
                "unique_together": {("ranch", "partner", "relation_type")},
            },
        ),
    ]
