# Generated by Django 5.1.15 on 2026-02-25 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0002_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgroSector",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sector_name", models.CharField(max_length=100, unique=True)),
                ("scian_code", models.CharField(blank=True, max_length=20)),
                ("activity_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "agro_sectors",
                "ordering": ["sector_name"],
            },
        ),
        migrations.CreateModel(
            name="AgroUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("Productor", "Productor"),
                            ("Acopiadora de grano", "Acopiadora de grano"),
                            ("Asociación agrícola", "Asociación agrícola"),
                            ("Empaque", "Empaque"),
                            ("Laboratorio", "Laboratorio"),
                            ("Consultoria", "Consultoria"),
                            ("Otro", "Otro"),
                        ],
                        default="Productor",
                        max_length=25,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "tax_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RFC", "RFC"),
                            ("Tax ID", "Tax ID"),
                            ("CUIT", "CUIT"),
                            ("RIF", "RIF"),
                            ("TIN", "TIN"),
                            ("SSN", "SSN"),
                            ("NIF", "NIF"),
                            ("CIF", "CIF"),
                            ("RUT", "RUT"),
                            ("Otro", "Otro"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("commercial_name", models.CharField(max_length=200)),
                ("headcount", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("location_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("suspended", "Suspendido"),
                            ("pending", "Pendiente"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("additional_params", models.JSONField(blank=True, default=dict)),
                ("attachments_url", models.JSONField(blank=True, default=list)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "agro_sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agro_units",
                        to="organizations.agrosector",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agro_units",
                        to="geography.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agro_units",
                        to="geography.state",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agro_units",
                "ordering": ["commercial_name"],
            },
        ),
    ]
